version: '3'

services:
  nginx:
    image: "nginx:1.16-alpine"
    ports:
      - "8674:80"
    restart: always
    volumes:
      - "./nginx-conf/graphite.conf:/etc/nginx/conf.d/default.conf:ro"
      - "graphite_static_files:/usr/share/nginx/html/static/:ro"
    depends_on:
      - graphite

  carbon:
    build: .
    command: "/opt/graphite/bin/run_carbon_cache.sh"
    ports:
      - "2003:2003"
    restart: always
    volumes:
      - "whisper_data:/opt/graphite/storage/whisper"
      - "./run_carbon_cache.sh:/opt/graphite/bin/run_carbon_cache.sh"
      - "./conf:/opt/graphite/conf"
      #- "./graphite.db:/opt/graphite/storage/graphite.db"

  graphite:
    build: .
    command: "/opt/graphite/bin/run_graphite_web.sh"
    ports:
      - "9674:8080"
    restart: always
    volumes:
      - "whisper_data:/opt/graphite/storage/whisper"
      - "./run_graphite_web.sh:/opt/graphite/bin/run_graphite_web.sh"
      - "graphite_static_files:/opt/graphite/static"
      - "./conf:/opt/graphite/conf"
      - "./graphite-conf/local_settings.py:/opt/graphite/webapp/graphite/local_settings.py"
      #- "./graphite.db:/opt/graphite/storage/graphite.db"
    depends_on:
      - postgres

  postgres:
    image: "postgres:12-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 1515:8080

volumes:
  whisper_data: {}
  graphite_static_files: {}
