version: '3'

services:
  nginx:
    image: "nginx:1.16-alpine"
    ports:
      - "8674:80"
    restart: always
    volumes:
      - "./nginx-conf/graphite.conf:/etc/nginx/conf.d/default.conf:ro"
      - "graphite_static_files:/usr/share/nginx/html/static/:ro"
    depends_on:
      - graphite

  carbon:
    build: .
    command: "/opt/graphite/bin/run_carbon_cache.sh"
    ports:
      - "2003:2003"
    restart: always
    volumes:
      - "whisper_data:/opt/graphite/storage/whisper"
      - "./run_carbon_cache.sh:/opt/graphite/bin/run_carbon_cache.sh"
      - "./conf:/opt/graphite/conf"

  graphite:
    build: .
    command: "/opt/graphite/bin/run_graphite_web.sh"
    restart: always
    volumes:
      - "whisper_data:/opt/graphite/storage/whisper"
      - "./run_graphite_web.sh:/opt/graphite/bin/run_graphite_web.sh"
      - "graphite_static_files:/opt/graphite/static"
      # - "./graphite-conf/local_settings.py:/opt/graphite/webapp/graphite/local_settings.py"

volumes:
  whisper_data: {}
  graphite_static_files: {}
