version: '3'

services:
  proxy:
    image: "nginx:1.16-alpine"
    ports:
      - "9980:80"
    volumes:
      - "./proxy/html:/usr/share/nginx/html:ro"
      - "./proxy/proxy_server.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - hello_world
  hello_world:
    image: "nginx:1.16-alpine"
    ports:
      - "9999:80"
    volumes:
      - "./hello_world/html:/usr/share/nginx/html:ro"
