version: '3'

services:
  prometheus:
    image: "prom/prometheus:v2.12.0"
    ports:
      - "9090:9090"
    restart: always
    volumes:
    #  - "prometheus_data:/prometheus-data"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    #environment:
    #  KEY: value

volumes:
  prometheus_data: {}
